added probes to k8 manifest, added initialization for celery workers, refactored to use json str for data between workers/api, and misc cleanup.

diff --git a/kubernetes/deployment.yaml b/kubernetes/deployment.yaml
--- a/kubernetes/deployment.yaml
+++ b/kubernetes/deployment.yaml
@@ -1,60 +1,3 @@
-
-apiVersion: v1
-kind: Service
-metadata:
-  name: redis
-spec:
-  selector:
-    app: redis
-  ports:
-    - name: redis
-      port: 6379
-  clusterIP: None
-
----
-apiVersion: v1
-kind: Service
-metadata:
-  name: fast-api-service
-spec:
-  type: NodePort
-  selector:
-    app: fast-api
-  ports:
-    - name: http
-      port: 80
-      targetPort: 8000
-      nodePort: 32767
-
----
-apiVersion: v1
-kind: PersistentVolume
-metadata:
-  name: shared-volume
-spec:
-  storageClassName: manual
-  capacity:
-    storage: 1Gi
-  accessModes:
-    - ReadWriteOnce
-  persistentVolumeReclaimPolicy: Retain
-  hostPath:
-    path: /tmp/
-
----
-apiVersion: v1
-kind: PersistentVolumeClaim
-metadata:
-  name: shared-pvc1
-spec:
-  storageClassName: manual
-  accessModes:
-    - ReadWriteOnce
-  resources:
-    requests:
-      storage: 1Gi
-
----
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -72,19 +15,32 @@ spec:
       containers:
         - name: redis
           image: redis:latest
+          imagePullPolicy: IfNotPresent
           ports:
             - name: redis
               containerPort: 6379
+          # TODO decide on amount and type of probes
+          livenessProbe:
+            exec:
+              command:
+                - sh
+                - -c
+                - redis-cli ping | grep PONG
+            initialDelaySeconds: 25
+            periodSeconds: 10
+            timeoutSeconds: 5
+            successThreshold: 1
+            failureThreshold: 3
           envFrom:
             - configMapRef:
                 name: app-configs
           resources:
             limits:
-              cpu: "0.02"
-              memory: "64Mi"
+              cpu: "0.1"
+              memory: "128Mi"
             requests:
-              cpu: "0.01"
-              memory: "32Mi"
+              cpu: "0.05"
+              memory: "64Mi"
 
 ---
 apiVersion: apps/v1
@@ -95,7 +51,7 @@ spec:
   selector:
     matchLabels:
       app: celery-worker
-  replicas: 1
+  replicas: 2
   template:
     metadata:
       labels:
@@ -103,20 +59,57 @@ spec:
     spec:
       containers:
         - name: celery-worker
-          image: dockerman2322/celery:v2
+          image: dockerman2322/celery:test
+          imagePullPolicy: IfNotPresent
+
+          # Constantly checks that it can communicate with redis
+          readinessProbe:
+            exec:
+              command:
+                - sh
+                - -c
+                - >
+                  if redis-cli -h redis ping | grep -q PONG; then
+                    echo "ready"
+                    exit 0
+                  else
+                    echo "not ready"
+                    exit 1
+                  fi
+            initialDelaySeconds: 40
+            periodSeconds: 60
+            timeoutSeconds: 15
+            successThreshold: 1
+            failureThreshold: 3
+          lifecycle:
+            # Initializes the container with Whisper
+            postStart:
+              exec:
+                command:
+                  - sh
+                  - -c
+                  - |
+                    python3 initialize.py
+                    if [ $? -eq 0 ]; then
+                      echo "Validation successful"
+                    else
+                      echo "Validation failed, exiting"
+                      exit 1
+                    fi
+
           envFrom:
             - configMapRef:
                 name: app-configs
           volumeMounts:
             - name: shared-volume
-              mountPath: /app/input  # TODO change this over so it's outside of the app folder
+              mountPath: /input
           resources:
             limits:
-              cpu: "2"
-              memory: "1000Mi"
+              cpu: "1.5"
+              memory: "1200Mi"
             requests:
-              cpu: "1"
-              memory: "300Mi"
+              cpu: "1.25"
+              memory: "1000Mi"
       volumes:
         - name: shared-volume
           persistentVolumeClaim:
@@ -140,6 +133,7 @@ spec:
       containers:
         - name: flower
           image: mher/flower
+          imagePullPolicy: IfNotPresent
           envFrom:
             - configMapRef:
                 name: app-configs
@@ -147,10 +141,10 @@ spec:
             - containerPort: 8888
           resources:
             limits:
-              cpu: "0.05"
+              cpu: "0.075"
               memory: "128Mi"
             requests:
-              cpu: "0.02"
+              cpu: "0.05"
               memory: "64Mi"
 
 ---
@@ -170,16 +164,30 @@ spec:
     spec:
       containers:
         - name: fast-api
-          image: dockerman2322/fast-api:v2  # TODO clearly define CORS once testing done
+          image: dockerman2322/fast-api:test  # TODO clearly define CORS once testing done
+          imagePullPolicy: IfNotPresent
           envFrom:
             - configMapRef:
                 name: app-configs
           volumeMounts:
             - name: shared-volume
-              mountPath: /app/input
+              mountPath: /input
           ports:
             - name: fast-api
               containerPort: 8000
+          resources:
+            limits:
+              cpu: "0.125"
+              memory: "512Mi"
+            requests:
+              cpu: "0.075"
+              memory: "256Mi"
+          readinessProbe:
+            httpGet:
+              path: /api/healthcheck
+              port: 8000
+            initialDelaySeconds: 5
+            periodSeconds: 10
       volumes:
         - name: shared-volume
           persistentVolumeClaim:
